name = "vindecoder"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "vindecoder-db"
database_id = "649b6539-a86f-4952-adcc-669da7139af4"

[[kv_namespaces]]
binding = "CONFIG_KV"
id = "c422879f-0925-46aa-a77a-24cd345fd17b"
